 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pics", type: :request do
  # Doc. As you add validations to Doc, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Doc.create! valid_attributes
      get docs_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      doc = Doc.create! valid_attributes
      get doc_url(doc)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_doc_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      doc = Doc.create! valid_attributes
      get edit_doc_url(doc)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Doc" do
        expect {
          post docs_url, params: { doc: valid_attributes }
        }.to change(Doc, :count).by(1)
      end

      it "redirects to the created doc" do
        post docs_url, params: { doc: valid_attributes }
        expect(response).to redirect_to(doc_url(Doc.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Doc" do
        expect {
          post docs_url, params: { doc: invalid_attributes }
        }.to change(Doc, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post docs_url, params: { doc: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested doc" do
        doc = Doc.create! valid_attributes
        patch doc_url(doc), params: { doc: new_attributes }
        doc.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the doc" do
        doc = Doc.create! valid_attributes
        patch doc_url(doc), params: { doc: new_attributes }
        doc.reload
        expect(response).to redirect_to(doc_url(doc))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        doc = Doc.create! valid_attributes
        patch doc_url(doc), params: { doc: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested doc" do
      doc = Doc.create! valid_attributes
      expect {
        delete doc_url(doc)
      }.to change(Doc, :count).by(-1)
    end

    it "redirects to the docs list" do
      doc = Doc.create! valid_attributes
      delete doc_url(doc)
      expect(response).to redirect_to(docs_url)
    end
  end
end
