development:
  clients:
    default:
      database: <%= ENV['DEV_DATABASE'] %>
      hosts:
        # To connect localhost/spectfic IP where mongoD is running
        - 192.168.17.1:27017
      options:

  options:

test:
  clients:
    default:
      # To connect to cloud mongoD -- 
      # create local_env.yml, check "local_env_sample.yml" for reference
      uri: mongodb+srv://<%= ENV['DB_USER'] %>:<%= ENV['DB_PASSWORD'] %>@<%= ENV['CLUSTER_CONNECT_PATH'] %>/<%= ENV['TEST_DATABASE'] %>?retryWrites=true&w=majority
      options:
        server_selection_timeout: 30
        read:
          mode: :primary
        max_pool_size: 1
